### ISSUE TITLE
Zstd gives error

### ISSUE THREAD

**Issue by lavilao** [redicculus/arch2appimage#5]
Hi, I am trying to install mpv-full-git and am getting this error after everithing is downloaded
Traceback (most recent call last):
  File "/home/luis/Downloads/Compressed/arch2appimage-main/arch2appimage.py", line 155, in <module>
    utils.extract_zst("download", APP_DIR)
  File "/home/luis/Downloads/Compressed/arch2appimage-main/utils.py", line 139, in extract_zst
    dctx.copy_stream(ifh, ofh)
zstd.ZstdError: zstd decompressor error: Unknown frame descriptor
any idea how to fix it?
I am using manjaro if it matters

**Comment by lavilao** [comment]
after dowble check it seems that is not after downloads but after libxpresent is downloaded

**Comment by ruanformigoni** [comment]
I have the same error trying to bundle wine:

```sh
Downloading lib32-glu...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.6/141.6 kB • 337.8 kB/s • 0:00:00   
Downloading libsm...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB • 20.3 MB/s • 0:00:00   
Downloading lib32-libsm...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 kB • ? • 0:00:00   
Traceback (most recent call last):
  File "/home/ruan/Repositories/arch2appimage/arch2appimage.py", line 155, in <module>
    utils.extract_zst("download", APP_DIR)
  File "/home/ruan/Repositories/arch2appimage/utils.py", line 139, in extract_zst
    dctx.copy_stream(ifh, ofh)
zstd.ZstdError: zstd decompressor error: Unknown frame descriptor
```
